### ISSUE TITLE
The http://localhost:5000/ is blank after launching webui.py

### ISSUE THREAD

**Issue by hkdavechan** [joequant/sptrader#18]
hi, 

I launched the script/webui.py by pycharm. But my  http://localhost:5000/ is blank in chrome.

Did i missed something in the installation step?

thanks!

**Comment by hkdavechan** [comment]
I followed another closed issue on this project and found a similar question raised by others.

You advised to Run the commands

     npm install
     npm run build-js

i got the following error when in run **npm run build-js** 
```
(base) C:\temp\sptrader-master>npm run build-js
npm ERR! missing script: build-js

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-08-11T04_40_28_743Z-debug.log
```

And  static/bundle.js is still missing.

the debug.log is below:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-js' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose stack Error: missing script: build-js
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd C:\temp\sptrader-master
6 verbose Windows_NT 10.0.16299
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-js"
8 verbose node v8.11.3
9 verbose npm  v5.6.0
10 error missing script: build-js
11 verbose exit [ 1, true ]

```
